upstream kaimier_site_upstream {
  server kaimier-site:80;
}

upstream kaimier_admin_upstream {
  server kaimier-admin:80;
}

server {
  listen 80;
  server_name kaimier.com www.kaimier.com;
  return 301 https://$host$request_uri;
}

server {
  listen 443 ssl http2;
  server_name kaimier.com www.kaimier.com;

  ssl_certificate /etc/letsencrypt/live/kaimier.com/fullchain.pem;
  ssl_certificate_key /etc/letsencrypt/live/kaimier.com/privkey.pem;

  include /etc/nginx/local/gateway.conf;

  location = /admin {
    return 308 /admin/;
  }

  location /admin/ {
    proxy_pass http://kaimier_admin_upstream/;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
  }

  location / {
    proxy_pass http://kaimier_site_upstream;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
  }
}
