upstream kaimier_site_upstream {
  server kaimier-site:80;
}

server {
  listen 80;
  server_name kaimier.com www.kaimier.com local.kaimier.com;

  include /etc/nginx/local/gateway.conf;

  location / {
    proxy_pass http://kaimier_site_upstream;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
  }
}
